# Generated by Django 5.1.7 on 2025-05-07 14:22

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'departamento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GrupoEtnico',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'grupo_etnico',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IdentidadGenero',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'identidad_genero',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NivelEducativo',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nivel_educativo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ocupacion',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ocupacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrientacionSexual',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orientacion_sexual',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
            ],
            options={
                'db_table': 'pais',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RedSocial',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'red_social',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SectorEconomico',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sector_economico',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ServicioBasico',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'servicio_basico',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sexo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_contrato',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoDiscapacidad',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_discapacidad',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoDispositivo',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_dispositivo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_documento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoVivienda',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_vivienda',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='usuario_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='usuario_permissions', to='auth.permission')),
            ],
            options={
                'db_table': 'usuario',
                'managed': True,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('departamento', models.ForeignKey(db_column='departamento_id', on_delete=django.db.models.deletion.PROTECT, related_name='municipios', to='login.departamento')),
            ],
            options={
                'db_table': 'municipio',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='departamento',
            name='pais',
            field=models.ForeignKey(db_column='pais_id', on_delete=django.db.models.deletion.PROTECT, related_name='departamentos', to='login.pais'),
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('contratista', 'Contratista'), ('alcaldesa', 'Alcaldesa'), ('juridico', 'Jurídico'), ('contratacion', 'Contratación'), ('financiera', 'Financiera'), ('despacho', 'Despacho'), ('admin', 'Administrador')], db_column='rol', default='contratista', max_length=30)),
                ('primer_nombre', models.CharField(db_column='nombre1', max_length=50)),
                ('segundo_nombre', models.CharField(blank=True, db_column='nombre2', max_length=50, null=True)),
                ('apellido_paterno', models.CharField(db_column='apellido1', max_length=50)),
                ('apellido_materno', models.CharField(blank=True, db_column='apellido2', max_length=50, null=True)),
                ('fecha_expedicion', models.DateField(blank=True, db_column='fecha_expedicion', null=True)),
                ('no_identificacion', models.CharField(db_column='numero_documento', max_length=50, unique=True)),
                ('telefono', models.CharField(blank=True, db_column='telefono_principal', max_length=30, null=True)),
                ('nacionalidad', models.CharField(blank=True, max_length=50, null=True)),
                ('pertenencia_lgbti', models.BooleanField(default=False)),
                ('discapacidad', models.BooleanField(default=False)),
                ('victima_conflicto', models.BooleanField(default=False)),
                ('migrante', models.BooleanField(default=False)),
                ('poblacion_rural', models.BooleanField(default=False)),
                ('zona', models.CharField(blank=True, choices=[('urbana', 'Urbana'), ('rural', 'Rural')], max_length=10, null=True)),
                ('estrato_social', models.IntegerField(blank=True, null=True)),
                ('telefono_secundario', models.CharField(blank=True, max_length=30, null=True)),
                ('actualmente_estudia', models.BooleanField(default=False)),
                ('institucion', models.CharField(blank=True, max_length=255, null=True)),
                ('ingresos_mensuales', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_construccion', models.CharField(blank=True, choices=[('formal', 'Formal'), ('informal', 'Informal')], max_length=20, null=True)),
                ('numero_personas_hogar', models.IntegerField(blank=True, null=True)),
                ('afiliacion_salud', models.CharField(blank=True, choices=[('EPS', 'EPS'), ('subsidiado', 'Régimen Subsidiado'), ('no_afiliado', 'No afiliado')], max_length=50, null=True)),
                ('enfermedades_cronicas', models.CharField(blank=True, max_length=255, null=True)),
                ('acceso_servicios_salud', models.CharField(blank=True, choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], max_length=20, null=True)),
                ('acceso_internet', models.BooleanField(default=False)),
                ('direccion', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField(blank=True, db_column='fecha_nacimiento', null=True)),
                ('grupo_etnico', models.ForeignKey(blank=True, db_column='grupo_etnico', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='personas_residentes', to='login.grupoetnico')),
                ('identidad_genero', models.ForeignKey(blank=True, db_column='identidad_genero', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='login.identidadgenero')),
                ('lugar_nacimiento', models.ForeignKey(blank=True, db_column='lugar_nacimiento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='personas_lugar_nacimiento', to='login.municipio')),
                ('municipio_residencia', models.ForeignKey(blank=True, db_column='municipio_residencia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='login.municipio')),
                ('nivel_formacion', models.ForeignKey(blank=True, db_column='nivel_educativo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='login.niveleducativo')),
                ('orientacion_sexual', models.ForeignKey(blank=True, db_column='orientacion_sexual', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='login.orientacionsexual')),
                ('profesion', models.ForeignKey(blank=True, db_column='ocupacion_actual', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='login.ocupacion')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'persona',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PersonaCuentaBancaria',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('banco', models.CharField(db_column='banco', max_length=100)),
                ('tipo_cuenta_bancaria', models.CharField(db_column='tipo_cuenta_bancaria', max_length=100)),
                ('numero_cuenta_bancaria', models.CharField(db_column='numero_cuenta_bancaria', max_length=100)),
                ('pensionado', models.BooleanField(db_column='pensionado')),
                ('persona', models.OneToOneField(db_column='persona_id', on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_bancaria', to='login.persona')),
            ],
            options={
                'db_table': 'persona_cuenta_bancaria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PersonaRedSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.ForeignKey(db_column='persona_id', on_delete=django.db.models.deletion.CASCADE, to='login.persona')),
                ('red_social', models.ForeignKey(db_column='red_social_codigo', on_delete=django.db.models.deletion.CASCADE, to='login.redsocial')),
            ],
            options={
                'db_table': 'persona_red_social',
                'managed': True,
                'unique_together': {('persona', 'red_social')},
            },
        ),
        migrations.AddField(
            model_name='persona',
            name='redes_sociales_uso',
            field=models.ManyToManyField(related_name='personas', through='login.PersonaRedSocial', to='login.redsocial'),
        ),
        migrations.AddField(
            model_name='persona',
            name='sector_economico',
            field=models.ForeignKey(blank=True, db_column='sector_economico', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='login.sectoreconomico'),
        ),
        migrations.CreateModel(
            name='PersonaServicioBasico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.ForeignKey(db_column='persona_id', on_delete=django.db.models.deletion.CASCADE, to='login.persona')),
                ('servicio_basico', models.ForeignKey(db_column='servicio_basico_codigo', on_delete=django.db.models.deletion.CASCADE, to='login.serviciobasico')),
            ],
            options={
                'db_table': 'persona_servicio_basico',
                'managed': True,
                'unique_together': {('persona', 'servicio_basico')},
            },
        ),
        migrations.AddField(
            model_name='persona',
            name='servicios_basicos',
            field=models.ManyToManyField(related_name='personas', through='login.PersonaServicioBasico', to='login.serviciobasico'),
        ),
        migrations.AddField(
            model_name='persona',
            name='sexo_biologico',
            field=models.ForeignKey(blank=True, db_column='sexo_biologico', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='login.sexo'),
        ),
        migrations.AddField(
            model_name='persona',
            name='tipo_contrato',
            field=models.ForeignKey(blank=True, db_column='tipo_contrato', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='login.tipocontrato'),
        ),
        migrations.AddField(
            model_name='persona',
            name='tipo_discapacidad',
            field=models.ForeignKey(blank=True, db_column='tipo_discapacidad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='login.tipodiscapacidad'),
        ),
        migrations.CreateModel(
            name='PersonaTipoDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.ForeignKey(db_column='persona_id', on_delete=django.db.models.deletion.CASCADE, to='login.persona')),
                ('tipo_dispositivo', models.ForeignKey(db_column='tipo_dispositivo_codigo', on_delete=django.db.models.deletion.CASCADE, to='login.tipodispositivo')),
            ],
            options={
                'db_table': 'persona_tipo_dispositivo',
                'managed': True,
                'unique_together': {('persona', 'tipo_dispositivo')},
            },
        ),
        migrations.AddField(
            model_name='persona',
            name='tipo_dispositivo',
            field=models.ManyToManyField(related_name='personas', through='login.PersonaTipoDispositivo', to='login.tipodispositivo'),
        ),
        migrations.AddField(
            model_name='persona',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, db_column='tipo_documento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='login.tipodocumento'),
        ),
        migrations.AddField(
            model_name='persona',
            name='tipo_vivienda',
            field=models.ForeignKey(db_column='tipo_vivienda', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='login.tipovivienda'),
        ),
    ]
