# Generated by Django 5.1.7 on 2025-05-07 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratacion', '0001_initial'),
        ('login', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='usuario_registro',
            field=models.ForeignKey(db_column='usuario_registro', on_delete=django.db.models.deletion.DO_NOTHING, related_name='contratos_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='creada_por',
            field=models.ForeignKey(db_column='creada_por', on_delete=django.db.models.deletion.CASCADE, related_name='convocatorias_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documento',
            name='contratista',
            field=models.ForeignKey(db_column='contratista_id', on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='login.persona'),
        ),
        migrations.AddField(
            model_name='evaluacionhv',
            name='contratista',
            field=models.ForeignKey(db_column='contratista_id', on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='login.persona'),
        ),
        migrations.AddField(
            model_name='evaluacionhv',
            name='convocatoria',
            field=models.ForeignKey(db_column='convocatoria_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contratacion.convocatoria'),
        ),
        migrations.AddField(
            model_name='evaluacionhv',
            name='evaluador',
            field=models.ForeignKey(db_column='evaluador_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='funcionario', serialize=False, to='login.persona')),
                ('cargo', models.CharField(db_column='cargo', default='Sin cargo', max_length=255)),
                ('tipo_contrato', models.CharField(db_column='tipo_contrato', default='Prestación de servicios', max_length=255)),
                ('cps', models.CharField(db_column='cps', default='CPS0001', max_length=255)),
                ('area', models.ForeignKey(db_column='area_id', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='contratacion.area')),
            ],
            options={
                'db_table': 'funcionario',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='funcionario',
            field=models.ForeignKey(db_column='funcionario_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='contratos', to='contratacion.funcionario'),
        ),
        migrations.CreateModel(
            name='ModificacionContratacion',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('fecha_inicio_suspension', models.DateField(blank=True, db_column='fecha_inicio_suspension', null=True)),
                ('fecha_final_suspension', models.DateField(blank=True, db_column='fecha_final_suspension', null=True)),
                ('plazo_suspension', models.IntegerField(blank=True, db_column='plazo_suspension', null=True)),
                ('unidad_plazo', models.CharField(blank=True, db_column='unidad_plazo', max_length=50, null=True)),
                ('fecha_inicio_suspension2', models.DateField(blank=True, db_column='fecha_inicio_suspension2', null=True)),
                ('fecha_final_suspension2', models.DateField(blank=True, db_column='fecha_final_suspension2', null=True)),
                ('plazo_suspension2', models.IntegerField(blank=True, db_column='plazo_suspension2', null=True)),
                ('unidad_plazo2', models.CharField(blank=True, db_column='unidad_plazo2', max_length=50, null=True)),
                ('cedente', models.CharField(blank=True, db_column='cedente', max_length=255, null=True)),
                ('cesionario', models.CharField(blank=True, db_column='cesionario', max_length=255, null=True)),
                ('direccion_cedente', models.CharField(blank=True, db_column='direccion_cedente', max_length=255, null=True)),
                ('telefono_cedente', models.CharField(blank=True, db_column='telefono_cedente', max_length=50, null=True)),
                ('correo_cedente', models.EmailField(blank=True, db_column='correo_cedente', max_length=254, null=True)),
                ('identificacion_cedente', models.CharField(blank=True, db_column='identificacion_cedente', max_length=100, null=True)),
                ('fecha_modificacion_cesion', models.DateField(blank=True, db_column='fecha_modificacion_cesion', null=True)),
                ('fecha_inicio_cesion', models.DateField(blank=True, db_column='fecha_inicio_cesion', null=True)),
                ('sipse_adicion', models.CharField(blank=True, db_column='sipse_adicion', max_length=255, null=True)),
                ('fecha_terminacion_adicion', models.DateField(blank=True, db_column='fecha_terminacion_adicion', null=True)),
                ('tiempo_adicion', models.IntegerField(blank=True, db_column='tiempo_adicion', null=True)),
                ('valor_adicion', models.DecimalField(blank=True, db_column='valor_adicion', decimal_places=2, max_digits=14, null=True)),
                ('fecha_adicion', models.DateField(blank=True, db_column='fecha_adicion', null=True)),
                ('rp_adicion', models.CharField(blank=True, db_column='rp_adicion', max_length=255, null=True)),
                ('fecha_rp_adicion', models.DateField(blank=True, db_column='fecha_rp_adicion', null=True)),
                ('sipse_adicion_2', models.CharField(blank=True, db_column='sipse_adicion_2', max_length=255, null=True)),
                ('fecha_terminacion_adicion_2', models.DateField(blank=True, db_column='fecha_terminacion_adicion_2', null=True)),
                ('tiempo_adicion_2', models.IntegerField(blank=True, db_column='tiempo_adicion_2', null=True)),
                ('valor_adicion_2', models.DecimalField(blank=True, db_column='valor_adicion_2', decimal_places=2, max_digits=14, null=True)),
                ('fecha_adicion_2', models.DateField(blank=True, db_column='fecha_adicion_2', null=True)),
                ('rp_adicion_2', models.CharField(blank=True, db_column='rp_adicion_2', max_length=255, null=True)),
                ('fecha_rp_adicion_2', models.DateField(blank=True, db_column='fecha_rp_adicion_2', null=True)),
                ('fecha_prorroga', models.DateField(blank=True, db_column='fecha_prorroga', null=True)),
                ('plazo_prorroga', models.IntegerField(blank=True, db_column='plazo_prorroga', null=True)),
                ('nueva_fecha_terminacion', models.DateField(blank=True, db_column='nueva_fecha_terminacion', null=True)),
                ('fecha_prorroga_2', models.DateField(blank=True, db_column='fecha_prorroga_2', null=True)),
                ('plazo_prorroga_2', models.IntegerField(blank=True, db_column='plazo_prorroga_2', null=True)),
                ('nueva_fecha_terminacion_2', models.DateField(blank=True, db_column='nueva_fecha_terminacion_2', null=True)),
                ('fecha_prorroga_3', models.DateField(blank=True, db_column='fecha_prorroga_3', null=True)),
                ('plazo_prorroga_3', models.IntegerField(blank=True, db_column='plazo_prorroga_3', null=True)),
                ('nueva_fecha_terminacion_3', models.DateField(blank=True, db_column='nueva_fecha_terminacion_3', null=True)),
                ('revision_contractual', models.TextField(blank=True, db_column='revision_contractual', null=True)),
                ('crp', models.CharField(blank=True, db_column='crp', max_length=255, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='fecha_registro')),
                ('contrato', models.ForeignKey(db_column='contrato_id', on_delete=django.db.models.deletion.CASCADE, related_name='modificaciones', to='contratacion.contrato')),
            ],
            options={
                'db_table': 'modificacion_contratacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Subgrupo',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', default='Subgrupo X', max_length=255)),
                ('area', models.ForeignKey(db_column='area_id', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='subgrupos', to='contratacion.area')),
            ],
            options={
                'db_table': 'subgrupo',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='funcionario',
            name='subgrupo',
            field=models.ForeignKey(db_column='subgrupo_id', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='contratacion.subgrupo'),
        ),
    ]
