# Generated by Django 5.1.7 on 2025-03-26 18:16

import certificado.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratacion', '__first__'),
        ('login', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedente', models.CharField(max_length=255, verbose_name='Cedente')),
                ('cesionario', models.CharField(max_length=255, verbose_name='Cesionario')),
                ('fecha_cesion', models.DateField(verbose_name='Fecha de Cesión')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='login.persona')),
                ('role', models.CharField(max_length=255, verbose_name='Rol o Cargo')),
                ('CPS', models.CharField(max_length=255, verbose_name='CPS')),
                ('sitio_expedicion', models.CharField(max_length=255, verbose_name='Sitio de Expedición')),
                ('objeto', models.TextField(verbose_name='Objeto del Contrato')),
                ('obligaciones', models.TextField(verbose_name='Obligaciones')),
                ('vr_inicial_contrato', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Inicial del Contrato')),
                ('valor_mensual_honorarios', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Mensual de Honorarios')),
                ('fecha_suscripcion', models.DateField(verbose_name='Fecha de Suscripción')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_terminacion', models.DateField(validators=[certificado.models.validar_fecha_terminacion], verbose_name='Fecha de Terminación')),
                ('tiempo_ejecucion_dia', models.IntegerField(verbose_name='Tiempo de Ejecución (Días)')),
                ('año_contrato', models.IntegerField(verbose_name='Año del Contrato')),
                ('radicado', models.CharField(max_length=255, verbose_name='Radicado')),
                ('correo', models.EmailField(default='correo@example.com', max_length=255, unique=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('terminado', 'Terminado')], default='terminado', max_length=255, verbose_name='Estado')),
            ],
            bases=('login.persona',),
        ),
        migrations.CreateModel(
            name='Radicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=255, unique=True, verbose_name='Número de Radicado')),
                ('fecha_radicado', models.DateField(verbose_name='Fecha de Radicación')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratacion.contrato', verbose_name='Contrato Asociado')),
            ],
        ),
    ]
